spring:
  application:
    name: auto-qrplc-link
  profiles:
    active: dev
  main:
    web-application-type: none






plc:
  polling:
    interval: 1000     # ???????????1?

  heartbeat:
    enabled: true      # ????????
    interval: 5000     # ?????????????5?